export const AccountRoleType = {
  ADMIN: "ADMIN",
  STAFF: "STAFF",
  USER: "USER",
} as const;
export const AccountType = {
  CUSTODIAL_PERSONAL: "CUSTODIAL_PERSONAL",
  CUSTODIAL_BUSINESS: "CUSTODIAL_BUSINESS",
  CUSTODIAL_COMMUNITY: "CUSTODIAL_COMMUNITY",
  CUSTODIAL_SYSTEM: "CUSTODIAL_SYSTEM",
  NON_CUSTODIAL_PERSONAL: "NON_CUSTODIAL_PERSONAL",
  NON_CUSTODIAL_BUSINESS: "NON_CUSTODIAL_BUSINESS",
  NON_CUSTODIAL_COMMUNITY: "NON_CUSTODIAL_COMMUNITY",
  NON_CUSTODIAL_SYSTEM: "NON_CUSTODIAL_SYSTEM",
};

export const InterfaceType = {
  USSD: "USSD",
  TELEGRAM: "TELEGRAM",
  APP: "APP",
};
