packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.6.0
  prettier: ^3.3.2
  typescript: ^5.5.4
  zod: ^3.23.8
  viem: ^2.13.1
  kysely: ^0.27.3
  "@t3-oss/env-nextjs": ^0.10.1
  "@types/node": ^20.12.12

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
