/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Point = {
  x: number;
  y: number;
};

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AliasAlias {
  active: boolean | null;
  blockchain_address: string;
  created_at: Timestamp;
  id: number;
  primary_name: string;
  updated_at: Timestamp;
}

export interface AliasSchemaVersion {
  version: number;
}

export interface ChainDataFaucetGive {
  contract_address: string;
  give_value: Numeric;
  id: number;
  recipient_address: string;
  token_address: string;
  tx_id: number | null;
}

export interface ChainDataOwnershipChange {
  contract_address: string;
  id: number;
  new_owner: string;
  previous_owner: string;
  tx_id: number | null;
}

export interface ChainDataPoolDeposit {
  contract_address: string;
  id: number;
  in_value: Numeric;
  initiator_address: string;
  token_in_address: string;
  tx_id: number | null;
}

export interface ChainDataPools {
  contract_address: string;
  id: number;
  pool_name: string;
  pool_symbol: string;
  removed: boolean;
}

export interface ChainDataPoolSwap {
  contract_address: string;
  fee: Numeric;
  id: number;
  in_value: Numeric;
  initiator_address: string;
  out_value: Numeric;
  token_in_address: string;
  token_out_address: string;
  tx_id: number | null;
}

export interface ChainDataSchemaVersion {
  version: number;
}

export interface ChainDataTokenBurn {
  burn_value: Numeric;
  burner_address: string;
  contract_address: string;
  id: number;
  tx_id: number | null;
}

export interface ChainDataTokenMint {
  contract_address: string;
  id: number;
  mint_value: Numeric;
  minter_address: string;
  recipient_address: string;
  tx_id: number | null;
}

export interface ChainDataTokens {
  contract_address: string;
  id: number;
  removed: boolean;
  sink_address: string;
  token_decimals: number;
  token_name: string;
  token_symbol: string;
}

export interface ChainDataTokenTransfer {
  contract_address: string;
  id: number;
  recipient_address: string;
  sender_address: string;
  transfer_value: Numeric;
  tx_id: number | null;
}

export interface ChainDataTx {
  block_number: number;
  date_block: Timestamp;
  id: number;
  success: boolean;
  tx_hash: string;
}

export interface CustodialDispatch {
  created_at: Timestamp;
  id: number;
  otx_id: number | null;
  status: string;
  updated_at: Timestamp;
}

export interface CustodialDispatchStatusType {
  value: string;
}

export interface CustodialKeystore {
  active: boolean | null;
  created_at: Timestamp;
  id: number;
  private_key: string;
  public_key: string;
  updated_at: Timestamp;
}

export interface CustodialMasterKey {
  created_at: Timestamp;
  id: number;
  updated_at: Timestamp;
}

export interface CustodialNoncestore {
  keystore_id: number;
  next_nonce: number | null;
  updated_at: Timestamp;
}

export interface CustodialOtx {
  created_at: Timestamp;
  id: number;
  nonce: number;
  otx_type: string;
  raw_tx: string;
  replaced: boolean | null;
  signer_account: number;
  tracking_id: string;
  tx_hash: string;
  updated_at: Timestamp;
}

export interface CustodialOtxTxType {
  value: string;
}

export interface CustodialSchemaVersion {
  version: number;
}

export interface PoolRouterPoolAllowedTokens {
  created_at: Timestamp;
  pool_address: string;
  token_address: string;
  updated_at: Timestamp;
}

export interface PoolRouterPoolTokenExchangeRates {
  created_at: Timestamp;
  exchange_rate: Numeric;
  pool_address: string;
  token_address: string;
  updated_at: Timestamp;
}

export interface PoolRouterPoolTokenLimits {
  created_at: Timestamp;
  pool_address: string;
  token_address: string;
  token_limit: Numeric;
  updated_at: Timestamp;
}

export interface PoolRouterSchemaVersion {
  version: number;
}

export interface PoolRouterSwapPools {
  created_at: Timestamp;
  fee_address: string | null;
  fee_ppm: Numeric;
  owner_address: string;
  pool_address: string;
  pool_name: string;
  pool_symbol: string;
  price_index_quoter_address: string;
  token_limiter_address: string;
  token_registry_address: string;
  updated_at: Timestamp;
}

export interface PoolRouterTokens {
  created_at: Timestamp;
  token_address: string;
  token_decimals: number;
  token_name: string;
  token_owner: string;
  token_symbol: string;
  updated_at: Timestamp;
}

export interface SarafuNetworkAccountRoleType {
  value: string;
}

export interface SarafuNetworkAccounts {
  account_role: string;
  account_type: string;
  blockchain_address: string;
  created_at: Timestamp;
  default_voucher: string | null;
  gas_approver: number | null;
  gas_gift_status: string;
  id: number;
  user_identifier: number;
}

export interface SarafuNetworkAccountType {
  value: string;
}

export interface SarafuNetworkCommodityType {
  value: string;
}

export interface SarafuNetworkFieldReports {
  created_at: Timestamp;
  created_by: number;
  description: string;
  id: number;
  image_url: string | null;
  location: string | null;
  modified_by: number;
  period_from: Timestamp | null;
  period_to: Timestamp | null;
  rejection_reason: string | null;
  report: string;
  status: string;
  tags: string[] | null;
  title: string;
  updated_at: Timestamp;
  verified_by: number[] | null;
  vouchers: string[];
}

export interface SarafuNetworkFieldReportStatusType {
  value: string;
}

export interface SarafuNetworkGasGiftStatusType {
  value: string;
}

export interface SarafuNetworkGenderType {
  value: string;
}

export interface SarafuNetworkInterfaceType {
  value: string;
}

export interface SarafuNetworkMarketplaces {
  account: number;
  created_at: Timestamp;
  id: number;
  marketplace_name: string;
}

export interface SarafuNetworkPersonalInformation {
  family_name: string | null;
  gender: string | null;
  geo: Point | null;
  given_names: string | null;
  id: number;
  language_code: string | null;
  location_name: string | null;
  user_identifier: number;
  year_of_birth: number | null;
}

export interface SarafuNetworkProductListings {
  account: number;
  commodity_available: boolean | null;
  commodity_description: string;
  commodity_name: string;
  commodity_type: string;
  created_at: Timestamp;
  frequency: string;
  geo: Point | null;
  id: number;
  image_url: string | null;
  location_name: string;
  price: number | null;
  quantity: number;
  voucher: number;
}

export interface SarafuNetworkSchemaVersion {
  version: number;
}

export interface SarafuNetworkServiceType {
  value: string;
}

export interface SarafuNetworkSwapPools {
  banner_url: string | null;
  id: number;
  pool_address: string;
  swap_pool_description: string;
}

export interface SarafuNetworkSwapPoolTags {
  id: number;
  swap_pool: number;
  tag: number;
}

export interface SarafuNetworkTags {
  id: number;
  tag: string;
}

export interface SarafuNetworkTransactions {
  block_number: number;
  date_block: Timestamp;
  id: number;
  recipient_address: string;
  sender_address: string;
  success: boolean;
  tx_hash: string;
  tx_index: number;
  tx_type: string | null;
  tx_value: Int8;
  voucher_address: string;
}

export interface SarafuNetworkTxType {
  value: string;
}

export interface SarafuNetworkUsers {
  activated: boolean | null;
  created_at: Timestamp;
  id: number;
  interface_identifier: string;
  interface_type: string;
}

export interface SarafuNetworkVoucherCertifications {
  certificate_url_pointer: string;
  certifier: number;
  certifier_weight: Numeric;
  created_at: Timestamp;
  id: number;
  voucher: number;
}

export interface SarafuNetworkVoucherIssuers {
  active: boolean | null;
  backer: number;
  created_at: Timestamp;
  id: number;
  voucher: number;
}

export interface SarafuNetworkVouchers {
  active: boolean | null;
  banner_url: string | null;
  contract_version: string | null;
  created_at: Timestamp;
  geo: Point | null;
  icon_url: string | null;
  id: number;
  internal: boolean | null;
  location_name: string | null;
  radius: number | null;
  sink_address: string;
  symbol: string;
  uoa: string | null;
  voucher_address: string;
  voucher_description: string;
  voucher_email: string | null;
  voucher_name: string;
  voucher_type: string;
  voucher_uoa: string;
  voucher_value: number;
  voucher_website: string | null;
}

export interface SarafuNetworkVoucherTags {
  id: number;
  tag: number;
  voucher: number;
}

export interface SarafuNetworkVoucherType {
  value: string;
}

export interface SarafuNetworkVpa {
  created_at: Timestamp;
  id: number;
  linked_account: number;
  vpa: string;
}

export interface SchemaVersion {
  version: number;
}

export interface UssdAccounts {
  public_key: string;
  session_id: string;
}

export interface UssdKvVise {
  id: number;
  key: Buffer;
  updated: Timestamp;
  value: Buffer;
}

export interface DB {
  "alias.alias": AliasAlias;
  "alias.schema_version": AliasSchemaVersion;
  "chain_data.faucet_give": ChainDataFaucetGive;
  "chain_data.ownership_change": ChainDataOwnershipChange;
  "chain_data.pool_deposit": ChainDataPoolDeposit;
  "chain_data.pool_swap": ChainDataPoolSwap;
  "chain_data.pools": ChainDataPools;
  "chain_data.schema_version": ChainDataSchemaVersion;
  "chain_data.token_burn": ChainDataTokenBurn;
  "chain_data.token_mint": ChainDataTokenMint;
  "chain_data.token_transfer": ChainDataTokenTransfer;
  "chain_data.tokens": ChainDataTokens;
  "chain_data.tx": ChainDataTx;
  "custodial.dispatch": CustodialDispatch;
  "custodial.dispatch_status_type": CustodialDispatchStatusType;
  "custodial.keystore": CustodialKeystore;
  "custodial.master_key": CustodialMasterKey;
  "custodial.noncestore": CustodialNoncestore;
  "custodial.otx": CustodialOtx;
  "custodial.otx_tx_type": CustodialOtxTxType;
  "custodial.schema_version": CustodialSchemaVersion;
  "pool_router.pool_allowed_tokens": PoolRouterPoolAllowedTokens;
  "pool_router.pool_token_exchange_rates": PoolRouterPoolTokenExchangeRates;
  "pool_router.pool_token_limits": PoolRouterPoolTokenLimits;
  "pool_router.schema_version": PoolRouterSchemaVersion;
  "pool_router.swap_pools": PoolRouterSwapPools;
  "pool_router.tokens": PoolRouterTokens;
  "sarafu_network.account_role_type": SarafuNetworkAccountRoleType;
  "sarafu_network.account_type": SarafuNetworkAccountType;
  "sarafu_network.accounts": SarafuNetworkAccounts;
  "sarafu_network.commodity_type": SarafuNetworkCommodityType;
  "sarafu_network.field_report_status_type": SarafuNetworkFieldReportStatusType;
  "sarafu_network.field_reports": SarafuNetworkFieldReports;
  "sarafu_network.gas_gift_status_type": SarafuNetworkGasGiftStatusType;
  "sarafu_network.gender_type": SarafuNetworkGenderType;
  "sarafu_network.interface_type": SarafuNetworkInterfaceType;
  "sarafu_network.marketplaces": SarafuNetworkMarketplaces;
  "sarafu_network.personal_information": SarafuNetworkPersonalInformation;
  "sarafu_network.product_listings": SarafuNetworkProductListings;
  "sarafu_network.schema_version": SarafuNetworkSchemaVersion;
  "sarafu_network.service_type": SarafuNetworkServiceType;
  "sarafu_network.swap_pool_tags": SarafuNetworkSwapPoolTags;
  "sarafu_network.swap_pools": SarafuNetworkSwapPools;
  "sarafu_network.tags": SarafuNetworkTags;
  "sarafu_network.transactions": SarafuNetworkTransactions;
  "sarafu_network.tx_type": SarafuNetworkTxType;
  "sarafu_network.users": SarafuNetworkUsers;
  "sarafu_network.voucher_certifications": SarafuNetworkVoucherCertifications;
  "sarafu_network.voucher_issuers": SarafuNetworkVoucherIssuers;
  "sarafu_network.voucher_tags": SarafuNetworkVoucherTags;
  "sarafu_network.voucher_type": SarafuNetworkVoucherType;
  "sarafu_network.vouchers": SarafuNetworkVouchers;
  "sarafu_network.vpa": SarafuNetworkVpa;
  schema_version: SchemaVersion;
  ussd_accounts: UssdAccounts;
  "ussd.kv_vise": UssdKvVise;
}
