/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Point = {
  x: number;
  y: number;
};

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccountRoleType {
  value: string;
}

export interface Accounts {
  account_role: Generated<string>;
  account_type: string;
  blockchain_address: string;
  created_at: Generated<Timestamp>;
  default_voucher: string | null;
  gas_approver: number | null;
  gas_gift_status: Generated<string>;
  id: Generated<number>;
  onboarding_completed: Generated<boolean | null>;
  user_identifier: number;
}

export interface AccountType {
  value: string;
}

export interface CommodityType {
  value: string;
}

export interface FieldReports {
  created_at: Generated<Timestamp>;
  created_by: number;
  description: string;
  id: Generated<number>;
  image_url: string | null;
  location: string | null;
  modified_by: number;
  period_from: Timestamp | null;
  period_to: Timestamp | null;
  rejection_reason: string | null;
  report: string;
  status: Generated<string>;
  tags: string[] | null;
  title: string;
  updated_at: Generated<Timestamp>;
  verified_by: number[] | null;
  vouchers: string[];
}

export interface FieldReportStatusType {
  value: string;
}

export interface GasGiftStatusType {
  value: string;
}

export interface GenderType {
  value: string;
}

export interface InterfaceType {
  value: string;
}

export interface PersonalInformation {
  bio: string | null;
  date_of_birth: Timestamp | null;
  email: string | null;
  family_name: string | null;
  gender: string | null;
  geo: Point | null;
  given_names: string | null;
  id: Generated<number>;
  language_code: Generated<string | null>;
  location_name: string | null;
  profile_photo_url: string | null;
  user_identifier: number;
  year_of_birth: number | null;
}

export interface ProductListings {
  account: number;
  commodity_available: Generated<boolean | null>;
  commodity_description: string;
  commodity_name: string;
  commodity_type: string;
  created_at: Generated<Timestamp>;
  frequency: string;
  geo: Point | null;
  id: Generated<number>;
  image_url: string | null;
  location_name: string;
  price: Generated<number | null>;
  quantity: number;
  unit: string | null;
  voucher: number;
}

export interface ProductListingTags {
  id: Generated<number>;
  product_listing: number;
  tag: number;
}

export interface SchemaVersion {
  version: number;
}

export interface ServiceType {
  value: string;
}

export interface SwapPools {
  banner_url: string | null;
  custom_terms_and_conditions: string | null;
  default_voucher: Generated<string>;
  geo: Point | null;
  id: Generated<number>;
  pool_address: string;
  pool_name: string | null;
  swap_pool_description: string;
  unit_of_account: string | null;
}

export interface SwapPoolTags {
  id: Generated<number>;
  swap_pool: number;
  tag: number;
}

export interface Tags {
  id: Generated<number>;
  tag: string;
}

export interface TxType {
  value: string;
}

export interface Users {
  activated: Generated<boolean | null>;
  created_at: Generated<Timestamp>;
  email: string | null;
  email_verified: Generated<boolean | null>;
  id: Generated<number>;
  interface_identifier: string;
  interface_type: string;
}

export interface VoucherIssuers {
  active: Generated<boolean | null>;
  backer: number;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  voucher: number;
}

export interface Vouchers {
  active: Generated<boolean | null>;
  banner_url: string | null;
  contract_version: string | null;
  created_at: Generated<Timestamp>;
  custom_terms_and_conditions: string | null;
  geo: Point | null;
  icon_url: string | null;
  id: Generated<number>;
  internal: Generated<boolean | null>;
  location_name: string | null;
  radius: number | null;
  sink_address: string;
  symbol: string;
  voucher_address: string;
  voucher_description: string;
  voucher_email: string | null;
  voucher_name: string;
  voucher_type: Generated<string>;
  voucher_uoa: Generated<string>;
  voucher_value: Generated<number>;
  voucher_website: string | null;
}

export interface VoucherType {
  value: string;
}

export interface DB {
  account_role_type: AccountRoleType;
  account_type: AccountType;
  accounts: Accounts;
  commodity_type: CommodityType;
  field_report_status_type: FieldReportStatusType;
  field_reports: FieldReports;
  gas_gift_status_type: GasGiftStatusType;
  gender_type: GenderType;
  interface_type: InterfaceType;
  personal_information: PersonalInformation;
  product_listing_tags: ProductListingTags;
  product_listings: ProductListings;
  schema_version: SchemaVersion;
  service_type: ServiceType;
  swap_pool_tags: SwapPoolTags;
  swap_pools: SwapPools;
  tags: Tags;
  tx_type: TxType;
  users: Users;
  voucher_issuers: VoucherIssuers;
  voucher_type: VoucherType;
  vouchers: Vouchers;
}
