/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string>;

export type Timestamp = ColumnType<Date, Date | string>;

export interface FaucetGive {
  contract_address: Generated<string>;
  give_value: Numeric;
  id: Generated<number>;
  recipient_address: string;
  token_address: string;
  tx_id: number | null;
}

export interface OwnershipChange {
  contract_address: Generated<string>;
  id: Generated<number>;
  new_owner: Generated<string>;
  previous_owner: Generated<string>;
  tx_id: number | null;
}

export interface PoolDeposit {
  contract_address: Generated<string>;
  id: Generated<number>;
  in_value: Numeric;
  initiator_address: string;
  token_in_address: string;
  tx_id: number | null;
}

export interface Pools {
  contract_address: Generated<string>;
  id: Generated<number>;
  pool_name: string;
  pool_symbol: string;
  removed: Generated<boolean>;
}

export interface PoolSwap {
  contract_address: Generated<string>;
  fee: Numeric;
  id: Generated<number>;
  in_value: Numeric;
  initiator_address: string;
  out_value: Numeric;
  token_in_address: string;
  token_out_address: string;
  tx_id: number | null;
}

export interface SchemaVersion {
  version: number;
}

export interface TokenBurn {
  burn_value: Numeric;
  burner_address: string;
  contract_address: Generated<string>;
  id: Generated<number>;
  tx_id: number | null;
}

export interface TokenMint {
  contract_address: Generated<string>;
  id: Generated<number>;
  mint_value: Numeric;
  minter_address: string;
  recipient_address: string;
  tx_id: number | null;
}

export interface Tokens {
  contract_address: Generated<string>;
  id: Generated<number>;
  removed: Generated<boolean>;
  sink_address: Generated<string>;
  token_decimals: number;
  token_name: string;
  token_symbol: string;
}

export interface TokenTransfer {
  contract_address: Generated<string>;
  id: Generated<number>;
  recipient_address: string;
  sender_address: string;
  transfer_value: Numeric;
  tx_id: number | null;
}

export interface Tx {
  block_number: number;
  date_block: Timestamp;
  id: Generated<number>;
  success: boolean;
  tx_hash: string;
}

export interface DB {
  faucet_give: FaucetGive;
  ownership_change: OwnershipChange;
  pool_deposit: PoolDeposit;
  pool_swap: PoolSwap;
  pools: Pools;
  schema_version: SchemaVersion;
  token_burn: TokenBurn;
  token_mint: TokenMint;
  token_transfer: TokenTransfer;
  tokens: Tokens;
  tx: Tx;
}
